version: '3'
services:
  nats:
    image: nats:latest
    command:
      - "-js"
      - "--tlscert"
      - "${TLS_CERT}"
      - "--tlskey"
      - "${TLS_KEY}"
      - "--tlscacert"
      - "${TLS_CA}"
    environment:
      - "STREAM_NAME=${STREAM_NAME}"
    ports:
      - "4222:4222"

  ${SERVICE_NAME}:
    build: ./src/deepthought/services/${SERVICE_NAME}
    env_file:
      - ./src/deepthought/services/${SERVICE_NAME}/nats.env.example
    environment:
      - "NATS_URL=nats://nats:4222"
      - "STREAM_NAME=${STREAM_NAME}"
    depends_on:
      - nats
