version: '3.8'
services:
  nats:
    image: nats:latest
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  memgraph:
    image: memgraph/memgraph
    ports:
      - "7687:7687"

  neo4j:
    image: neo4j:5
    ports:
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/test

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"

  ume:
    image: redpandadata/redpanda:latest
    command:
      - redpanda
      - start
      - --smp
      - "1"
      - --overprovisioned
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://localhost:9092
      - --advertise-kafka-addr
      - PLAINTEXT://ume:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
