version: '3.8'
services:
  nats:
    image: nats:latest
    command: ["-js"]
    ports:
      - "4222:4222"
      - "8222:8222"

  memgraph:
    image: memgraph/memgraph
    ports:
      - "7687:7687"

  chroma:
    image: chromadb/chroma
    ports:
      - "8000:8000"
