[build-system]
requires = [
    "setuptools>=61",
    "setuptools_scm[toml]>=6.3",
]
build-backend = "setuptools.build_meta"

[project]
name = "dtrt-finetune"
dynamic = ["version"]
dependencies = ["deepthought-rethought"]

[project.scripts]
dtrt-finetune = "deepthought.train:main"

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"
