name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: diff
        env:
          GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python scripts/check_code_changes.py | tee result.txt
          echo "changed=$(cat result.txt)" >> "$GITHUB_OUTPUT"

  lint_and_test:
    needs: detect_changes
    if: needs.detect_changes.outputs.code_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
        
          python-version: '3.x'
      - id: requirements-hash
        run: echo "hash=$(pip hash requirements-ci.txt | awk 'NR==2 {print \$1}' | cut -d: -f2)" >> "$GITHUB_OUTPUT"
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.requirements-hash.outputs.hash }}
          restore-keys: |
            pip-

      - run: pip install -r requirements-ci.txt
      - run: pip install -e . --no-deps
      - run: flake8 src tests
      - env:
          PYTHONPATH: src
        run: pytest --cov=src --cov-report=xml
      - uses: codecov/codecov-action@v3
        with:
          files: coverage.xml
