name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - 'examples/**'
      - '**/*.py'
      - '**/*.cs'
    paths-ignore:
      - 'docs/**'
      - '**/*.md'
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - 'examples/**'
      - '**/*.py'
      - '**/*.cs'

permissions:
  contents: read

# limit to one concurrent run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect_changes:
    runs-on: ["self-hosted", "linux"]
    outputs:
      code_changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - id: diff
        env:
          GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python scripts/check_code_changes.py | tee result.txt
          echo "changed=$(cat result.txt)" >> "$GITHUB_OUTPUT"

  lint_and_test:
    needs: detect_changes
    if: needs.detect_changes.outputs.code_changed == 'true'
    runs-on: ["self-hosted", "linux"]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start NATS container
        run: |
          docker run -d --name dtr_nats \
            -p 4222:4222 -p 8222:8222 nats:latest -js
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-ci.txt
      - run: pip install -e . --no-deps
      - name: Run pre-commit
        if: matrix.python-version == '3.11'
        run: pre-commit run --all-files
      - name: Setup JetStream
        run: python setup_jetstream.py
      - env:
          PYTHONPATH: src
        run: pytest --cov=src --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Cleanup NATS container
        if: always()
        run: docker rm -f dtr_nats
