name: CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'src/**'
      - 'tests/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Check code changes
        id: code_changed
        run: |
          # Skip lint and tests when only comments or blank lines change
          base=$(git rev-parse HEAD^ 2>/dev/null || git rev-list --max-parents=0 HEAD)
          files=$(git diff --name-only "$base" HEAD -- 'src/**' 'tests/**')
          if [ -z "$files" ]; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
            exit 0
          fi
          for f in $files; do
            if git diff -U0 "$base" HEAD -- "$f" \
                | grep -E '^[+-]' \
                | grep -vE '^(\+\+\+|---)' \
                | grep -vqE '^[+-]\s*(#|"""|\'\'\'|$)'; then
              echo "changed=true" >> "$GITHUB_OUTPUT"
              exit 0
            fi
          done
          echo "changed=false" >> "$GITHUB_OUTPUT"
      - name: Install dependencies
        if: steps.code_changed.outputs.changed == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
      - name: Run flake8
        if: steps.code_changed.outputs.changed == 'true'
        run: flake8 src tests
      - name: Run pytest
        if: steps.code_changed.outputs.changed == 'true'
        run: pytest -q
