name: CI

on:
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - 'examples/**'
      - '**/*.py'
      - '**/*.cs'
  push:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'scripts/**'
      - 'examples/**'
      - '**/*.py'
      - '**/*.cs'

# limit to one concurrent run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# limit to one concurrent run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# limit to one concurrent run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      code_changed: ${{ steps.diff.outputs.changed }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: diff
        env:
          GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          python scripts/check_code_changes.py | tee result.txt
          echo "changed=$(cat result.txt)" >> "$GITHUB_OUTPUT"

  lint_and_test:
    needs: detect_changes
    if: needs.detect_changes.outputs.code_changed == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Start NATS container
        run: |
          docker run -d --name dtr_nats \
            -p 4222:4222 -p 8222:8222 nats:latest -js
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - id: requirements-hash
        run: |
          echo "hash=$(pip hash requirements-ci.txt | \
            awk 'NR==2 {print \$1}' | cut -d: -f2)" >> "$GITHUB_OUTPUT"
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: pip-${{ steps.requirements-hash.outputs.hash }}
          restore-keys: |
            pip-
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-ci.txt
      - run: pip install -e . --no-deps
      - run: pre-commit run --all-files
      - name: Setup JetStream
        run: python setup_jetstream.py
      - env:
          PYTHONPATH: src
        run: pytest --cov=src --cov-report=xml
      - uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: coverage.xml
      - name: Cleanup NATS container
        if: always()
        run: docker rm -f dtr_nats
