name: Release

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: read

# limit to one concurrent run per branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ["self-hosted", "linux"]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel twine
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*
      - name: Publish to PyPI
        if: secrets.PYPI_API_TOKEN != ''
        uses: pypa/gh-action-pypi-publish@v1.8.11
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
          skip-existing: true
