name: Replay

on:
  pull_request:
    paths:
      - 'tools/**'
      - 'src/**'
      - 'tests/replay_basic.py'
      - '.github/workflows/replay.yml'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  replay:
    runs-on: ['self-hosted', 'linux']
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-ci.txt
      - run: pip install -e . --no-deps
      - env:
          PYTHONPATH: src
        run: pytest tests/replay_basic.py
